name: first workflow

on:
  push:
    branches:
      - main
env:
  WORKFLOW_OWNER: satishmishra
jobs:
  job-1:
    runs-on: self-hosted
    env:
      JOB_OWNER: job1_env
    steps:
      - name: Access env and print it
        run: echo $WORKFLOW_OWNER
      - name: Job 1 env runner
        run: echo $JOB_OWNER
  job-2:
    runs-on: self-hosted
    needs: 
      - job-1
    env:
      JOB_OWNER_2: job2_env
    steps:
      - name: Access env for workflow and print it
        run: echo $WORKFLOW_OWNER
      - name: job 1 env runner
        run: echo $JOB_OWNER
      - name: job 2 env runner
        run: echo $JOB_OWNER_2
  job-3:
    runs-on: self-hosted
    steps:
      - name: define the env in step level
        env:
          STEP_1_ENV: step1env
        run: echo "hello"
      - name: define the env in step 2 level
        env:
          STEP_2_ENV: step2env
        run: echo $STEP_1_ENV
      
